=== paulswartz/schemas/schemas/com.mbta.ctd.subwayside.train-heartbeat.json
{
  "$id": "https://github.com/mbta/schemas/blob/main/schemas/com.mbta.ctd.subwayside.train-heartbeat.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "Train Heartbeat message received by the wayside server",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "cloudevents.json#/properties/id",
      "examples": ["200081266220230427135628421"]
    },
    "source": {
      "$ref": "cloudevents.json#/properties/source",
      "examples": ["hsctdprd.mbta.com/subwayside-12345"]
    },
    "specversion": {
      "const": "1.0",
      "$ref": "cloudevents.json#/properties/specversion"
    },
    "type": {
      "const": "com.mbta.ctd.subwayside.train-heartbeat",
      "$ref": "cloudevents.json#/properties/type"
    },
    "time": {
      "$ref": "cloudevents.json#/properties/time"
    },
    "partitionkey": {
      "type": "string",
      "minLength": 1,
      "description": "Key used to balance messages across multiple shards",
      "examples": ["O200812662"]
    },
    "data": {
      "description": "The event payload.",
      "$ref": "#/$defs/datadef"
    }
  },
  "required": [
    "id",
    "source",
    "specversion",
    "type",
    "data",
    "time",
    "partitionkey"
  ],
  "$defs": {
    "carNumber": {
      "type": "string",
      "description": "The 4 digit number of a car",
      "pattern": "^\\d{4}$"
    },
    "timestamp": {
      "description": "RFC3339 timestamp",
      "type": "string",
      "format": "date-time",
      "pattern": "^\\d{4}-(0\\d|1[012])-([012]\\d|3[01])T([01]\\d|2[0-3]):([0-5]\\d):([0-5]\\d)([.]\\d{1,6})?(Z|[+-]\\d{1,2}:[0-5]\\d)$"
    },
    "trainFlags": {
      "type": "object",
      "required": [
        "carNbrValid",
        "transmissionDtValid",
        "shopMode",
        "timeSyncGps",
        "speedValid",
        "gpsValid",
        "operationDataValid",
        "ptuConnected",
        "cellularUp",
        "wifiUp",
        "modemGwuc",
        "critical",
        "dead"
      ],
      "properties": {
        "carNbrValid": { "type": "boolean" },
        "transmissionDtValid": { "type": "boolean" },
        "shopMode": { "type": "boolean" },
        "timeSyncGps": { "type": "boolean" },
        "speedValid": { "type": "boolean" },
        "gpsValid": { "type": "boolean" },
        "operationDataValid": { "type": "boolean" },
        "ptuConnected": { "type": "boolean" },
        "cellularUp": { "type": "boolean" },
        "wifiUp": {
          "type": "array",
          "minItems": 0,
          "maxItems": 2,
          "items": { "type": "boolean" }
        },
        "modemGwuc": { "type": "boolean" },
        "critical": { "type": "boolean" },
        "dead": { "type": "boolean" }
      }
    },
    "carFlags": {
      "type": "object",
      "required": [
        "online",
        "master",
        "faultLog",
        "mileageValid",
        "maintenancePasswordVersionValid"
      ],
      "properties": {
        "online": { "type": "boolean" },
        "master": { "type": "boolean" },
        "faultLog": { "type": "boolean" },
        "mileageValid": { "type": "boolean" },
        "maintenancePasswordVersionValid": { "type": "boolean" }
      }
    },
    "location": {
      "type": "object",
      "required": ["id", "name"],
      "properties": {
        "id": { "type": "number", "minimum": 1 },
        "name": { "type": "string", "minLength": 1 }
      }
    },
    "system": {
      "type": "object",
      "required": ["online"],
      "properties": {
        "valid": { "type": "boolean" },
        "online": { "type": "boolean" },
        "fault": { "type": "boolean" },
        "faultSeverity": { "type": "integer", "minimum": 0, "maximum": 3 }
      }
    },
    "car": {
      "type": "object",
      "required": [
        "nbr",
        "type",
        "flags",
        "maintenancePasswordVersion",
        "mileageMi",
        "systems",
        "faultSeverity",
        "airSpringPressure",
        "loadWeightLb",
        "gwucWanState",
        "wifiState"
      ],
      "properties": {
        "nbr": { "$ref": "#/$defs/carNumber" },
        "type": { "type": "string", "enum": ["UNKNOWN", "CAB", "NON_CAB"] },
        "flags": { "$ref": "#/$defs/carFlags" },
        "maintenancePasswordVersion": {
          "type": "string",
          "pattern": "^\\d+[.]\\d+$"
        },
        "mileageMi": {
          "type": "number",
          "minimum": 0
        },
        "systems": {
          "type": "object",
          "required": [
            "gcu1",
            "gcu2",
            "api",
            "atpN",
            "atpR",
            "nvr",
            "vms",
            "mcu",
            "dcuA1",
            "dcuA2",
            "dcuB1",
            "dcuB2",
            "dcuC1",
            "dcuC2",
            "dcuD1",
            "dcuD2",
            "dcuE1",
            "dcuE2",
            "dcuF1",
            "dcuF2",
            "dcuG1",
            "dcuG2",
            "dcuH1",
            "dcuH2",
            "ers",
            "mbcu1",
            "mbcu2",
            "hvac1",
            "hvac2",
            "pcu1",
            "pcu2",
            "lvps",
            "gwuc"
          ],
          "properties": {
            "gcu1": { "$ref": "#/$defs/system" },
            "gcu2": { "$ref": "#/$defs/system" },
            "api": { "$ref": "#/$defs/system" },
            "atpN": { "$ref": "#/$defs/system" },
            "atpR": { "$ref": "#/$defs/system" },
            "nvr": { "$ref": "#/$defs/system" },
            "vms": { "$ref": "#/$defs/system" },
            "mcu": { "$ref": "#/$defs/system" },
            "dcuA1": { "$ref": "#/$defs/system" },
            "dcuA2": { "$ref": "#/$defs/system" },
            "dcuB1": { "$ref": "#/$defs/system" },
            "dcuB2": { "$ref": "#/$defs/system" },
            "dcuC1": { "$ref": "#/$defs/system" },
            "dcuC2": { "$ref": "#/$defs/system" },
            "dcuD1": { "$ref": "#/$defs/system" },
            "dcuD2": { "$ref": "#/$defs/system" },
            "dcuE1": { "$ref": "#/$defs/system" },
            "dcuE2": { "$ref": "#/$defs/system" },
            "dcuF1": { "$ref": "#/$defs/system" },
            "dcuF2": { "$ref": "#/$defs/system" },
            "dcuG1": { "$ref": "#/$defs/system" },
            "dcuG2": { "$ref": "#/$defs/system" },
            "dcuH1": { "$ref": "#/$defs/system" },
            "dcuH2": { "$ref": "#/$defs/system" },
            "ers": { "$ref": "#/$defs/system" },
            "mbcu1": { "$ref": "#/$defs/system" },
            "mbcu2": { "$ref": "#/$defs/system" },
            "hvac1": { "$ref": "#/$defs/system" },
            "hvac2": { "$ref": "#/$defs/system" },
            "pcu1": { "$ref": "#/$defs/system" },
            "pcu2": { "$ref": "#/$defs/system" },
            "lvps": { "$ref": "#/$defs/system" },
            "gwuc": { "$ref": "#/$defs/system" }
          }
        },
        "faultSeverity": {
          "oneOf": [
            {
              "type": "string",
              "enum": ["NORMAL", "FUNCTIONAL_FAULT", "SYSTEM_FAILURE"]
            },
            { "type": "null" }
          ]
        },
        "airSpringPressure": {
          "type": "array",
          "minItems": 2,
          "maxItems": 2,
          "items": {
            "type": "integer",
            "minimum": 0
          }
        },
        "loadWeightLb": {
          "type": "array",
          "minItems": 2,
          "maxItems": 2,
          "items": {
            "type": "integer",
            "minimum": 0
          }
        },
        "gwucWanState": {
          "type": "string",
          "enum": [
            "UNKNOWN",
            "INITIALIZING",
            "SIM_MISSING",
            "SIM_READY",
            "CONNECTING",
            "CONNECTION_FAILURE",
            "CONNECTED",
            "DISCONNECTED",
            "PIN_CODE_ERROR",
            "DISABLED"
          ]
        },
        "wifiState": {
          "type": "array",
          "minItems": 2,
          "maxItems": 2,
          "items": {
            "type": "string",
            "enum": ["UNKNOWN", "CONNECTING", "CONNECTED", "DISABLED"]
          }
        }
      }
    },
    "datadef": {
      "type": "object",
      "required": [
        "receivedDt",
        "createdDt",
        "transmissionDt",
        "flags",
        "commId",
        "commCarNbr",
        "activeCarNbr",
        "primaryCarNbr",
        "sourceCarNbr",
        "leadCarNbr",
        "operationLine",
        "trainDirection",
        "numberOfCars",
        "leaderMcuCarNbr",
        "masterMcuCarNbrs",
        "cars",
        "speedMph",
        "latitude",
        "longitude",
        "destinationStation",
        "currentStation",
        "nextStation",
        "runningDistanceMi",
        "routeCode"
      ],
      "properties": {
        "receivedDt": {
          "$ref": "#/$defs/timestamp"
        },
        "createdDt": {
          "$ref": "#/$defs/timestamp"
        },
        "transmissionDt": {
          "$ref": "#/$defs/timestamp"
        },
        "flags": {
          "$ref": "#/$defs/trainFlags"
        },
        "commId": {
          "type": "integer",
          "minimum": 1,
          "maximum": 65535
        },
        "commCarNbr": { "$ref": "#/$defs/carNumber" },
        "activeCarNbr": { "$ref": "#/$defs/carNumber" },
        "primaryCarNbr": { "$ref": "#/$defs/carNumber" },
        "sourceCarNbr": { "$ref": "#/$defs/carNumber" },
        "leadCarNbr": { "$ref": "#/$defs/carNumber" },
        "operationLine": {
          "type": "string",
          "enum": ["Orange", "Red"]
        },
        "trainDirection": {
          "type": "string",
          "enum": ["NONE", "LEFT", "RIGHT", "UNKNOWN"]
        },
        "leaderMcuCarNbr": { "$ref": "#/$defs/carNumber" },
        "masterMcuCarNbrs": {
          "type": "array",
          "minItems": 1,
          "maxItems": 6,
          "items": {
            "$ref": "#/$defs/carNumber"
          }
        },
        "numberOfCars": {
          "type": "integer",
          "minimum": 1,
          "maximum": 6
        },
        "cars": {
          "type": "array",
          "minItems": 1,
          "maxItems": 6,
          "items": {
            "$ref": "#/$defs/car"
          }
        },
        "speedMph": {
          "type": "number",
          "minimum": 0
        },
        "latitude": {
          "type": "number",
          "minimum": -90,
          "maximum": 90
        },
        "longitude": {
          "type": "number",
          "minimum": -180,
          "maximum": 180
        },
        "destinationStation": {
          "oneOf": [{ "$ref": "#/$defs/location" }, { "type": "null" }]
        },
        "currentStation": {
          "oneOf": [{ "$ref": "#/$defs/location" }, { "type": "null" }]
        },
        "nextStation": {
          "oneOf": [{ "$ref": "#/$defs/location" }, { "type": "null" }]
        },
        "runningDistanceMi": {
          "type": "number",
          "minimum": 0
        },
        "routeCode": {
          "type": "string",
          "minLength": 4
        }
      }
    }
  }
}

=== paulswartz/schemas/examples/com.mbta.ctd.subwayside.train-heartbeat/basic.json
{
  "specversion": "1.0",
  "type": "com.mbta.ctd.subwayside.train-heartbeat",
  "id": "200081266220230427135628421",
  "source": "hsctdprd.mbta.com/subwayside-12345",
  "time": "2023-05-22T13:32:45Z",
  "partitionkey": "O2000812662",
  "data": {
    "receivedDt": "2023-04-27T13:56:28.420999Z",
    "createdDt": "2023-05-22T13:32:45Z",
    "transmissionDt": "2023-05-22T13:33:00Z",
    "flags": {
      "carNbrValid": true,
      "transmissionDtValid": true,
      "shopMode": false,
      "timeSyncGps": true,
      "speedValid": true,
      "gpsValid": true,
      "operationDataValid": true,
      "ptuConnected": true,
      "cellularUp": false,
      "wifiUp": [false, false],
      "modemGwuc": true,
      "critical": true,
      "dead": false
    },
    "commId": 51462,
    "commCarNbr": "1445",
    "activeCarNbr": "1445",
    "primaryCarNbr": "1445",
    "sourceCarNbr": "1445",
    "leadCarNbr": "1445",
    "operationLine": "Orange",
    "trainDirection": "LEFT",
    "numberOfCars": 6,
    "leaderMcuCarNbr": "1445",
    "masterMcuCarNbrs": ["1234", "2345"],
    "cars": [
      {
        "nbr": "1445",
        "type": "CAB",
        "flags": {
          "online": true,
          "master": true,
          "faultLog": false,
          "mileageValid": true,
          "maintenancePasswordVersionValid": true
        },
        "maintenancePasswordVersion": "00.00",
        "mileageMi": 78920.9846,
        "systems": {
          "gcu1": { "online": false },
          "gcu2": { "online": false },
          "api": { "online": false },
          "atpN": { "online": false },
          "atpR": { "online": false },
          "nvr": { "online": false },
          "vms": { "online": false },
          "mcu": { "online": false },
          "dcuA1": { "online": false },
          "dcuA2": { "online": false },
          "dcuB1": { "online": false },
          "dcuB2": { "online": false },
          "dcuC1": { "online": false },
          "dcuC2": { "online": false },
          "dcuD1": { "online": false },
          "dcuD2": { "online": false },
          "dcuE1": { "online": false },
          "dcuE2": { "online": false },
          "dcuF1": { "online": false },
          "dcuF2": { "online": false },
          "dcuG1": { "online": false },
          "dcuG2": { "online": false },
          "dcuH1": { "online": false },
          "dcuH2": { "online": false },
          "ers": { "online": false },
          "mbcu1": {
            "valid": true,
            "online": false,
            "faultSeverity": 0,
            "fault": false
          },
          "mbcu2": { "online": false },
          "hvac1": { "online": false },
          "hvac2": { "online": false },
          "pcu1": { "online": false },
          "pcu2": { "online": false },
          "lvps": { "online": false },
          "gwuc": { "online": false }
        },
        "faultSeverity": null,
        "airSpringPressure": [564, 564],
        "loadWeightLb": [79280, 79280],
        "gwucWanState": "INITIALIZING",
        "wifiState": ["CONNECTING", "DISABLED"]
      }
    ],
    "speedMph": 5,
    "latitude": 42.437278,
    "longitude": -71.07084,
    "destinationStation": null,
    "currentStation": {
      "id": 376,
      "name": "Malden Center"
    },
    "nextStation": null,
    "runningDistanceMi": 11.147,
    "routeCode": "1002"
  }
}
