=== paulswartz/schemas/schemas/com.mbta.ctd.glides.editors_changed.v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/mbta/schemas/blob/main/schemas/com.mbta.ctd.glides.editors_changed.v1.json",
  "description": "Editors Changed",
  "type": "object",
  "properties": {
    "type": { "const": "com.mbta.ctd.glides.editors_changed.v1" },
    "specversion": { "const": "1.0" },
    "source": { "$ref": "glides-events.json#/properties/source" },
    "id": { "$ref": "glides-events.json#/properties/id" },
    "time": { "$ref": "glides-events.json#/$defs/timestamp" },
    "data": {
      "type": "object",
      "properties": {
        "metadata": { "$ref": "glides-events.json#/$defs/metadata" },
        "changes": {
          "type": "array",
          "items": { "$ref": "#/$defs/editor_change" }
        }
      },
      "required": ["metadata", "changes"]
    }
  },
  "required": ["type", "specversion", "source", "id", "time", "data"],
  "$defs": {
    "editor_change": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "oneOf": [{ "const": "start" }, { "const": "stop" }]
        },
        "location": { "$ref": "glides-events.json#/$defs/location" },
        "editor": { "$ref": "glides-events.json#/$defs/glides_user" }
      },
      "required": ["type", "location", "editor"]
    }
  }
}

=== paulswartz/schemas/examples/glides-events/editors_changed.v1.take_over.json
{
  "type": "com.mbta.ctd.glides.editors_changed.v1",
  "specversion": "1.0",
  "source": "glides.mbta.com",
  "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
  "time": "2023-01-20T09:30:00-05:00",
  "data": {
    "metadata": {
      "author": {
        "emailAddress": "ainspector@example.com",
        "badgeNumber": "123"
      },
      "inputTimestamp": "2023-01-20T09:29:59-05:00",
      "inputType": "take-over-editing",
      "location": { "odsId": "lakst" }
    },
    "changes": [
      {
        "type": "stop",
        "location": { "odsId": "lakst" },
        "editor": {
          "emailAddress": "binspector@example.com",
          "badgeNumber": "456"
        }
      },
      {
        "type": "start",
        "location": { "odsId": "lakst" },
        "editor": {
          "emailAddress": "ainspector@example.com",
          "badgeNumber": "123"
        }
      }
    ]
  }
}
