=== paulswartz/schemas/schemas/com.mbta.ctd.glides.operator_signed_in.v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/mbta/schemas/blob/main/schemas/com.mbta.ctd.glides.operator_signed_in.v1.json",
  "description": "Operator Signed In",
  "type": "object",
  "properties": {
    "type": { "const": "com.mbta.ctd.glides.operator_signed_in.v1" },
    "specversion": { "const": "1.0" },
    "source": { "$ref": "glides-events.json#/properties/source" },
    "id": { "$ref": "glides-events.json#/properties/id" },
    "time": { "$ref": "glides-events.json#/$defs/timestamp" },
    "data": {
      "type": "object",
      "properties": {
        "metadata": { "$ref": "glides-events.json#/$defs/metadata" },
        "operator": { "$ref": "glides-events.json#/$defs/operator" },
        "signedInAt": { "$ref": "glides-events.json#/$defs/timestamp" },
        "signature": { "$ref": "#/$defs/signature" }
      },
      "required": ["metadata"]
    }
  },
  "required": ["type", "specversion", "source", "id", "time", "data"],
  "$defs": {
    "signature": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "examples": ["tap", "type"]
        }
      }
    }
  }
}

=== paulswartz/schemas/examples/glides-events/operator_signed_in.v1.json
{
  "type": "com.mbta.ctd.glides.operator_signed_in.v1",
  "specversion": "1.0",
  "source": "glides.mbta.com",
  "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
  "time": "2023-01-20T09:30:00-05:00",
  "data": {
    "metadata": {
      "author": {
        "emailAddress": "ainspector@example.com",
        "badgeNumber": "123"
      },
      "inputTimestamp": "2023-01-20T09:29:59-05:00",
      "inputType": "sign-in",
      "location": { "odsId": "lakst" }
    },
    "operator": { "badgeNumber": "789" },
    "signedInAt": "2023-01-20T09:45:00-05:00",
    "signature": { "type": "tap" }
  }
}
