=== paulswartz/schemas/schemas/glides-events.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/mbta/schemas/blob/main/schemas/glides-events.json",
  "title": "Glides Events",
  "description": "Kinesis events emitted by Glides",
  "$ref": "cloudevents.json",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "description": "name of the event",
      "$comment": "enforced to be a valid event name by the oneOf, below"
    },
    "specversion": { "const": "1.0" },
    "source": {
      "$ref": "cloudevents.json#/properties/source",
      "examples": [
        "glides.mbta.com",
        "glides-dev.mbtace.com",
        "glides-dev-green.mbtace.com"
      ]
    },
    "id": { "type": "string", "minLength": 1 },
    "time": { "$ref": "#/$defs/timestamp" },
    "data": {
      "type": "object",
      "properties": {
        "metadata": { "$ref": "#/$defs/metadata" }
      },
      "required": ["metadata"],
      "$comment": "other fields validated by the oneOf, below"
    }
  },
  "required": ["type", "specversion", "source", "id", "time", "data"],
  "oneOf": [
    {
      "properties": {
        "type": { "const": "com.mbta.ctd.glides.editors_changed.v1" }
      },
      "$ref": "com.mbta.ctd.glides.editors_changed.v1.json#/"
    },
    {
      "properties": {
        "type": { "const": "com.mbta.ctd.glides.operator_signed_in.v1" }
      },
      "$ref": "com.mbta.ctd.glides.operator_signed_in.v1.json#/"
    },
    {
      "properties": {
        "type": { "const": "com.mbta.ctd.glides.trips_updated.v1" }
      },
      "$ref": "com.mbta.ctd.glides.trips_updated.v1.json#/"
    }
  ],
  "$defs": {
    "badge_number": {
      "type": "string",
      "minLength": 1,
      "pattern": "^[1-9][0-9]*$",
      "$comment": "without any leading 0s"
    },
    "email_address": {
      "$comment": "format validation isn't supported everywhere, so also do some simple string checks",
      "type": "string",
      "minLength": 3,
      "format": "email",
      "pattern": "@"
    },
    "glides_user": {
      "type": "object",
      "properties": {
        "emailAddress": { "$ref": "#/$defs/email_address" },
        "badgeNumber": { "$ref": "#/$defs/badge_number" }
      },
      "required": ["emailAddress"]
    },
    "location": {
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "gtfsId": { "type": "string", "minLength": 1 }
          },
          "required": ["gtfsId"]
        },
        {
          "properties": {
            "odsId": { "type": "string", "minLength": 1 }
          },
          "required": ["odsId"]
        }
      ]
    },
    "metadata": {
      "type": "object",
      "properties": {
        "author": { "$ref": "#/$defs/glides_user" },
        "inputTimestamp": { "$ref": "#/$defs/timestamp" },
        "inputType": { "type": "string", "minLength": 1 },
        "location": { "$ref": "#/$defs/location" }
      }
    },
    "operator": {
      "type": "object",
      "properties": {
        "badgeNumber": { "$ref": "#/$defs/badge_number" }
      },
      "required": ["badgeNumber"]
    },
    "timestamp": {
      "type": "string",
      "minLength": 20,
      "$comment": "RFC3339 timestamp",
      "format": "date-time",
      "pattern": "^[0-9]{4}-[01][0-9]-[0-3][0-9]T[012][0-9]:[0-5][0-9]:[0-6][0-9](.[0-9]*)?(Z|[+-][012][0-9]:[0-5][0-9])$",
      "examples": ["2023-01-20T09:30:00-05:00"]
    }
  }
}

=== paulswartz/schemas/examples/glides-events/trips_updated.v1.dropped_and_headway.json
[
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "dropped-trip"
      },
      "tripUpdates": [
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "10:05:00",
            "endTime": "10:52:00"
          },
          "dropped": { "reason": "staffing" },
          "scheduled": { "scheduledCars": [{}] }
        },
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-gover" },
            "endLocation": { "gtfsId": "place-lake" },
            "startTime": "10:55:00",
            "endTime": "10:42:00"
          },
          "dropped": { "reason": "staffing" },
          "scheduled": { "scheduledCars": [{}] }
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "manage-headways"
      },
      "tripUpdates": [
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "09:55:00",
            "endTime": "10:42:00"
          },
          "startTime": "09:56:00",
          "scheduled": { "scheduledCars": [{}] }
        },
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "10:00:00",
            "endTime": "10:47:00"
          },
          "startTime": "10:02:00",
          "scheduled": { "scheduledCars": [{}] }
        },
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "10:10:00",
            "endTime": "10:57:00"
          },
          "startTime": "10:08:00",
          "scheduled": { "scheduledCars": [{}] }
        }
      ]
    }
  }
]

=== paulswartz/schemas/examples/glides-events/trips_updated.v1.split.json
[
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "dropped-trip"
      },
      "tripUpdates": [
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "10:00:00",
            "endTime": "10:47:00"
          },
          "dropped": { "reason": "ran as single" },
          "scheduled": {
            "scheduledCars": [
              {
                "run": "506",
                "operator": { "badgeNumber": "678" }
              },
              {
                "run": "507",
                "operator": { "badgeNumber": "789" }
              }
            ]
          }
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "edit-trip"
      },
      "tripUpdates": [
        {
          "type": "updated",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "startLocation": { "gtfsId": "place-lake" },
            "endLocation": { "gtfsId": "place-gover" },
            "startTime": "09:55:00",
            "endTime": "10:42:00"
          },
          "comment": "single",
          "cars": [
            {
              "label": "3800",
              "operator": { "badgeNumber": "456" }
            }
          ],
          "scheduled": {
            "scheduledCars": [
              {
                "run": "504",
                "operator": { "badgeNumber": "456" }
              },
              {
                "run": "505",
                "operator": { "badgeNumber": "567" }
              }
            ]
          }
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.trips_updated.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2023-01-20T09:30:00-05:00",
    "data": {
      "metadata": {
        "inputType": "add-trip"
      },
      "tripUpdates": [
        {
          "type": "added",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "glidesId": "ADDED-1"
          },
          "startLocation": { "gtfsId": "place-lake" },
          "startTime": "10:00:00",
          "cars": [
            {
              "label": "3850",
              "operator": { "badgeNumber": "567" }
            }
          ],
          "scheduled": null
        },
        {
          "type": "added",
          "tripKey": {
            "serviceDate": "2022-01-20",
            "glidesId": "ADDED-2"
          },
          "endLocation": { "gtfsId": "place-lake" },
          "previousTripKey": {
            "serviceDate": "2022-01-20",
            "glidesId": "ADDED-1"
          },
          "cars": [
            {
              "label": "3850",
              "operator": { "badgeNumber": "567" }
            }
          ],
          "scheduled": null
        }
      ]
    }
  }
]

=== paulswartz/schemas/examples/glides-events/trips_updated.v1.delay.json
{
  "type": "com.mbta.ctd.glides.trips_updated.v1",
  "specversion": "1.0",
  "source": "glides.mbta.com",
  "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
  "time": "2023-01-23T01:25:00-05:00",
  "data": {
    "metadata": {
      "inputType": "edit-trip"
    },
    "tripUpdates": [
      {
        "type": "updated",
        "tripKey": {
          "serviceDate": "2023-01-22",
          "startLocation": { "gtfsId": "place-matt" },
          "endLocation": { "gtfsId": "place-ashmt" },
          "startTime": "25:30:00",
          "endTime": "25:38:00"
        },
        "startTime": "25:45:00",
        "scheduled": {
          "scheduledCars": [
            {
              "run": "500",
              "operator": { "badgeNumber": "1234" }
            }
          ]
        }
      }
    ]
  }
}
